[workspace]
resolver = "2"
members = ["qcd-sme"]

[workspace.dependencies]
peroxide = { git = "https://github.com/GComitini/peroxide", rev = "f982dbee", features = ["plot", "complex"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
