[workspace]
resolver = "2"
members = ["qcd-sme"]

[workspace.dependencies]
peroxide = { git = "https://github.com/GComitini/peroxide", rev = "6789b68b", features = ["plot", "complex"] }
serial_test = "3.1"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
